# Project Details
sonar.verbose=true
sonar.projectKey=valaxy30-key_twittertrend
sonar.projectName=twittertrend
sonar.organization=valaxy30-key
sonar.language=java

# Source Code
sonar.sources=src/main/java


# Java Binaries
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude folders

# Test Reports (Optional)

# Code Coverage (Optional)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml